#!/bin/bash


HTTPD_LANG=${HTTPD_LANG-"C"}
HTTPD_LOG_LEVEL=${HTTPD_LOGLEVEL:-info}


# Apache gets grumpy about PID files pre-existing
rm -f /var/run/httpd/httpd.pid 

cd ~
    echo "Starting Kazoo-UI ..."
    exec httpd -f /etc/httpd/conf/httpd.conf -e $HTTPD_LOG_LEVEL -DFOREGROUND
