#!/bin/bash


HTTPD_LANG=${HTTPD_LANG-"C"}
HTTPD_LOG_LEVEL=${HTTPD_LOGLEVEL:-info}
: ${CROSSBAR_URI:=https://api.valuphone.com}

rm -f /var/run/httpd/httpd.pid 

cd ~
    echo "Starting Kazoo-UI ..."
    exec httpd -f /etc/httpd/conf/httpd.conf -e $HTTPD_LOG_LEVEL -DFOREGROUND
